### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by renatonlima** [akretion/ak-odoo-incubator#56]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

# Modules to migrate

- [ ] account_chart_multicompany
- [ ] account_invoice_allowed_product
- [ ] account_journal_sale_refund_link
- [ ] account_move_line_mass_edit_account
- [ ] active_previous_actived_cron
- [ ] attachment_base_synchronize
- [ ] base_compute_field_after_install
- [x] base_jsonify
- [x] base_sparse_field
- [ ] completely_available_picking
- [ ] delivery_carrier_url
- [ ] demo_sale
- [ ] external_file_location
- [ ] gollum
- [ ] keychain
- [ ] onchange_helper
- [ ] orm_helper
- [ ] partner_comment_on_sale_stock
- [ ] prevent2make_order
- [ ] product_pricelist_per_product_import_export
- [ ] product_supplier_import_export
- [ ] product_unsmart_button
- [ ] product_variant_import_export
- [ ] product_weight_variant
- [ ] production_release
- [ ] public_price_keeper
- [ ] sale_price_origin
- [ ] sale_simple_discount
- [ ] sales_team_multicompany
- [ ] stock_default_warehouse_by_company
- [ ] stock_inventory_export
- [ ] stock_picking_printed
- [ ] stock_product_supplier_code
- [ ] stock_reserve_location
- [ ] stock_warehouse_clean_delete
- [ ] web_colored_export

**Comment by bealdav** [comment]
Hi @renatonlima,
Thanks for this listing. 
I provided to Raphael a short list of these to do in short term (not all the modules). Have you this list ?
Thanks

**Comment by bealdav** [comment]
Please read this file https://github.com/akretion/ak-odoo-incubator/tree/10-product_unsmart_button

**Comment by bealdav** [comment]
From master branch:
git checkout -b 10-base_compute_field_after_install origin/master
git format-patch --stdout origin/master..origin/8.0 -- base_compute_field_after_install | git am -3

**Comment by hparfr** [comment]
```sh
# create empty branch from master
git checkout -b 10-base_compute_field_after_install origin/master
# fetch dir "base_compute_field_after_install" from 8.0 branch
git checkout 8.0 -- base_compute_field_after_install
```

**Comment by SalahAdDin** [comment]
What's about `product_variant_import_export` and `11.0`.
